dist: xenial
language: python
python: 3.7.2
install:
- pip install -r requirements.txt
deploy:
  provider: pypi
  user: '__token__'
  on:
    tags: true
    branch: master
    repo: PamCai/DLSuR
  skip_existing: true
  password:
    secure: H5ZHowvGnCpwo8jEiSxTXNqmYuL8u4bqSfsRLWpOTTjGvtLaHs276SDuahL5k7birRSDjQAG/apQIRQFhORv2y2dkcqZZyhXetMZpJKvfeN3wLCAbpVqjekvRHVAdBx2Kzko5lOrLuF4KiWwL6OFCD8BtKHjiuijI5ftmIBO6rPp6tVjMn86yon+hOuHOqUftwjMqANsby1STop2eE+6ZEiH0yNefh69RwmvfKhjw551xEg2krPtFozcZrOjTcw2EH8pLyKdy2VLc7Q7XMYENI2XJwjHpj6rUpHidKSHa7sEaZaQgY23Q0RNstsmHYPbbYnHpawFt6/8AYkBQpmfRdXxG9MXyTd98FG2ochVPbm4iAbEJg9cIWxQFrjTm4sU8RH+3/5it+JDEDETSpXFhGmoAUDNXxrJAKEMMBMwYO3qrqI3SVEXGw/7Ea1+9m3GL2BV2QvgO+Rk1XG26eLQZ8twBjBISlJtHyTZoD+TCcAtcypahWPszK6qzSGwLmMDPc87fwzwHetNWAC2kMYo+gpENku6gvRiMQdhfrw5H95uCl0UO80kxxT4ej2372SA+igKuLG5MYdFJaGt7hARvMIonZVO/cNbIDVbp3iCXyba4w0pQCqXyq3zyKOoCJG9vz3sF+HzwOqcu09i2mrrm1BXnua1FQnlB79HzgHjHT4=